
# custom myself assets in head
head:
  css:
  js:
    async:
    #aliyun iconfont
      iconfont: //at.alicdn.com/t/font_2562370_5ieunq9xazl.js
    

# SideBar Avatar
avatar:
  title : Marsyearの记录屋
  url: /avatar.png
  rounded: true
  opacity: 1

# site ico
favicon: /favicon.ico

colors:
  primary: "#2d609b"
  bg: "#FFF"
  selection_bg: "#79cafe" # 选取文字时的背景色
  # 标签云中标签的起始色和结束色
  # tag_start_color:
  # tag_end_color:

bg_image:
  enable: true
  url: /bg.png
  # dark:
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8

banner:
  title:
   - Mars
   - Year
   - の
   - 时光
   - 记录
   - 延续
  enable: true
  border: false
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

fireworks:
  enable: true
  colors:
    - "45, 96, 155"
    - "121, 202, 254"
    - "45, 96, 155"

cursor:
  enable: true
  default: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/pointer.cur
  pointer: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/link.cur
  text: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/css/md-cursors/text.cur