
# custom myself assets in head
head:
  css:
    base: /css/common.css
  js:
    async:
    #aliyun iconfont
      iconfont: //at.alicdn.com/t/font_2562370_5ieunq9xazl.js
    

# SideBar Avatar
avatar:
  title : Marsyearの记录屋
  url: /avatar.png
  rounded: true
  opacity: 1

# site ico
favicon: /favicon.ico

colors:
  primary: "#2d609b"
  bg: "#FFF"
  selection_bg: "#79cafe" # 选取文字时的背景色
  # 标签云中标签的起始色和结束色
  # tag_start_color:
  # tag_end_color:

bg_image:
  enable: true
  url: /bg.png
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8
  dark: /darkBg.png

# Index Slogan
banner:
  title:
   - Mars
   - Year
   - の
   - 日常
   - 回忆
   - 录
  enable: true
  border: false
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# Firework
fireworks:
  enable: true
  colors:
    - "45, 96, 155"
    - "121, 202, 254"
    - "45, 96, 155"

# Mouse Style
cursor:
  enable: true
  default: /pointer.cur
  pointer: /link.cur
  text: /text.cur
  
# CDN
cdn:
  pre: ""
  css:
  js:
    base:
    async:
      # 默认引入的图标资源，使用 iconfont
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js
    defer: