
# custom myself assets in head
head:
  css:
    base: /css/common.css
  js:
    async:
    #aliyun iconfont
      iconfont: //at.alicdn.com/t/font_2562370_d2noxce2sqr.js
    

# SideBar Avatar
avatar:
  title : 火星年的个人小站
  url: /avatar.png
  rounded: true
  opacity: 1

# site ico
favicon: /favicon.ico

colors:
  primary: "#2d609b"
  bg: "#FFF"
  selection_bg: "#79cafe" # 选取文字时的背景色
  # 标签云中标签的起始色和结束色
  # tag_start_color:
  # tag_end_color:

bg_image:
  enable: true
  url: /bg.png
  # blur: 30px # 设置背景模糊程度
  opacity: 0.8
  dark: /darkBg.png

# Index Slogan
banner:
  title:
   - Mars
   - Year
   - の
   - 日常
   - 回忆
   - 录
  enable: true
  border: false
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

# Firework
fireworks:
  enable: true
  colors:
    - "45, 96, 155"
    - "121, 202, 254"
    - "45, 96, 155"

# Mouse Style
cursor:
  enable: true
  default: /pointer.cur
  pointer: /link.cur
  text: /text.cur


menu:
  home:
    path: /
    icon: icon-home-4-line
  list:
    - type: archives
      path: /archives/
      icon: icon-archive-line
    - type: categories
      path: /categories/
      icon: icon-folder-2-line
    - type: tags
      path: /tags/
      icon: icon-price-tag-3-line
    # - path: https://www.yunyoujun.cn
    #   icon: icon-cloud-line
    #   count: 你猜
  custom:
    title: 文档
    path: https://yun.yunyoujun.cn
    icon: icon-settings-line

# sideMenu
social:
  - name: GitHub
    link: https://github.com/MarsYear
    icon: icon-github-line
    color: "#6e5494"
  - name: 哔哩哔哩
    link: https://space.bilibili.com/6686944?spm_id_from=333.1007.0.0
    icon: icon-bilibili-line
    color: "#FF8EB3"
  - name: E-Mail
    link: mailto:marsyear@gexiaowen.com
    icon: icon-mail-line
    color: "#8E71C1"  
  - name: PS账号
    link: /sony/psn
    icon: icon-playstation-
    color: "#0072d0" 
  - name: Xbox账号
    link: /microsoft/xbox
    icon: icon-xbox
    color: "green"
  - name: steam账号
    link: https://steamcommunity.com/profiles/76561198161303810/
    icon: icon-steam  
    color: "#182d5e"
  

# sideMenu下的醒目链接
pages:
  - name: 我的小伙伴们
    url: /links/
    icon: icon-genderless-line
    color: dodgerblue
  - name: 游玩的游戏
    url: /gamelist/
    icon: icon-Games-Folder
    color: "#4f85bc"


wordcloud:
  enable: true

# pay
reward:
  enable: false
  comment: 如果对你有帮助，那就投个币吧(｡◕∀◕｡)
  methods:
    - name: 支付宝
      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/alipay-qrcode.jpg
      color: "#00A3EE"
      icon: icon-alipay-line
    - name: 微信支付
      path: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/donate/wechatpay-qrcode.jpg
      color: "#2DC100"
      icon: icon-wechat-pay-line

comment:
  candidates:
    - waline
    # - giscus
  tips:
    - 如果您有任何关于博客内容的相关讨论，欢迎前往 <a href="https://github.com/MarsYear/blog/discussions/" target="_blank">GitHub Discussions</a> 与我交流。
  
footer:
  since: 2022
  beian:
    enable: true
    icp: 京ICP备2021037803号
  support:
    enable: false
    title: 又拍云
    link: https://www.upyun.com
    logo: https://cdn.jsdelivr.net/gh/YunYouJun/cdn/img/logo/upyun-logo.png
    prefix: 本网站由
    suffix: 提供 CDN 加速
  custom_text:    
  
# CDN
cdn:
  pre: ""
  css:
  js:
    base:
    async:
      # 默认引入的图标资源，使用 iconfont
      iconfont: //at.alicdn.com/t/font_1140697_dxory92pb0h.js
    defer:

# 默哀
mourn:
  enable: true
  days:
    - "4-4"
    - "5-12"
